Next-formalizationFull.hs
evdven/Next pull request #3
Opened 2017-03-27 06:44 UTC by uaksu

Average duration for events which change the ownership of the subject is added.
To handle agreements, I updated OEMEvent.oemEvtSubject characteristic as optional using Maybe. So far I used paymentRequired as a separator between invoice and delivery. But, here I see it is set as Always for a delivery also. If we say paymentRequired=Always for a delivery then there will be no difference between it and an invoice. How shall we continue?

2017-03-27 06:45 UTC, uaksu commented
Average duration for events which change the ownership of the subject is added.
To handle agreements, I updated OEMEvent.oemEvtSubject characteristic as optional using Maybe. So far I used paymentRequired as a separator between invoice and delivery. But, here I see it is set as Always for a delivery also. If we say paymentRequired=Always for a delivery then there will be no difference between it and an invoice. How shall we continue?

2017-03-27 08:11 UTC, evdven commented on Next-formalizationFull.hs
> +getActualStarDate e =  (getActualDate e) !! 1
why have implicit ordering? This is a bit tricky

2017-03-27 08:13 UTC, evdven requested changes

2017-03-27 08:13 UTC, evdven commented on Next-formalizationFull.hs
> +isdone e = if List.genericLength (getActualDate e) == 3 then True else False
hmmm. can we have more gentle definition here?

2017-03-27 08:13 UTC, evdven commented on Next-formalizationFull.hs
> +delivery1a = EventInstance{evtRef = deliveryEvent, evtInstName = "delivery1a", evtInstStyle = Regular, evtInstHasParty = True, evtInstParty = customer1, evtInstHasSubject = True, evtInstSubject = pro
can we have a clean explicit meaning on the dates which are irrespective of their order?

2017-03-29 06:56 UTC, uaksu commented on Next-formalizationFull.hs
> +delivery1a = EventInstance{evtRef = deliveryEvent, evtInstName = "delivery1a", evtInstStyle = Regular, evtInstHasParty = True, evtInstParty = customer1, evtInstHasSubject = True, evtInstSubject = pro
Based on Dennis' formalizations (https://www.dropbox.com/sh/wotluzcfcccm3rp/AAAOL7IqJk2OV96goCXHUXvPa?dl=0) the lifecycle (status) of an event instance will be determined using these dates , i.e. ToDo, Started, Done. For example, PlannedDate has three dates: the first one is for ToDo, the second one is for planned start, and the last one for the planned end date. However, I could not figure out why do we need ToDo date for ActualDate.

2017-03-29 07:01 UTC, uaksu commented on Next-formalizationFull.hs
> +isdone e = if List.genericLength (getActualDate e) == 3 then True else False
Do you mean should I add an explanation for isdone function or something else? isdone function looks at the actualDate field of an event instance and determines whether the event instance has a Done date.

2017-03-30 12:53 UTC, evdven commented on Next-formalizationFull.hs
> +isdone e = if List.genericLength (getActualDate e) == 3 then True else False
I'm looking for a more clean declarative meaninfull definition like

type Date = (Integer, Integer, Integer)
data Timing = Timing {begin :: Date, end :: Date} deriving (Eq, Show)

data EventInstance = EventInstance {name :: String, planned :: Timing, actual :: Timing} deriving (Eq, Show)

event1 = EventInstance{name = "My first event!", planned = Timing{begin = (5, 1, 2017), end = (10, 2, 2017)}, actual = Timing {begin = (6, 1, 2017), end = (16, 3, 2017)}}

showme = begin (planned event1)

2017-03-31 17:50 UTC, merged